name: IONOS.space

on: [push]

jobs:
  ionos-space:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get Ionos Project data
        uses: buildwith-ionos/retrieve-project-info-action@v0.1.3
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: 35346700-6a3c-43f8-a074-a5b21d21b737
          service-host: api-eu.ionos.space
      - name: Setup Node.js 12.16.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        run: npm ci
      - name: Build Node project
        run: npm run build
        env:
          SITE_URL: ${{ steps.project.outputs.site-url }}
          CI: true
      - name: Deploy to IONOS
        uses: buildwith-ionos/deploy-to-ionos-action@v0.1.3
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          dist-folder: dist
          service-host: api-eu.ionos.space
          project: 35346700-6a3c-43f8-a074-a5b21d21b737
          remote-host: ${{ steps.project.outputs.remote-host }}
